### ISSUE TITLE
not support redhat8.2

### ISSUE THREAD

**Issue by meteor199** [Tongsuo-Project/curl#6]
### I did this

在redhat上报错
./sync/curl-Linux: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by ./sync/curl-Linux)
./sync/curl-Linux: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./sync/curl-Linux)

版本号
NAME="Red Hat Enterprise Linux"
VERSION="8.2 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.2"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.2 (Ootpa)"
ANSI_COLOR="0;31"

linux版本：
Linux CNPAPP04 4.18.0-372.57.1.el8_6.x86_64 #1 SMP Thu May 11 07:38:47 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux

### I expected the following

release中的curl默认支持低版本linux

### curl/libcurl version

[v2023.10.31-SM](https://github.com/Tongsuo-Project/curl/releases/tag/v2023.10.31-SM)

### operating system

Red Hat Enterprise Linux 8.2 (Ootpa)

**Comment by dongbeiouba** [comment]
发布的Linux版curl是基于GitHub提供的ubuntu-20.04系统，可能存在glic版本兼容性问题。

你直接使用源代码编译吧，参考一下https://www.tongsuo.net/docs/features/curl
